//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DopeTrax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public System.Guid SongId { get; set; }
        public string SongTitle { get; set; }
        public string C_ArtistName { get; set; }
        public string SongDuration { get; set; }
        public int BeatsPerMinute { get; set; }
    }
}
